# RewAD3: PD, DD and DPD
# Pilot Study: Probability Discounting only
# check python-generated trials for run B
library(tidyverse)
library(readr)

##### Data Import

# Subject ID
#id <- "example" # (= run B, generated by Python, for simulated run A)
id <- "0ko4o6yky"

# Import Genereated Trials
path_trials <- paste("../../data/", id, "_params_exp2_z.csv", sep="")
#trials <- read_delim(path_trials, ";", escape_double = FALSE, trim_ws = TRUE)
trials <- read_csv(path_trials)

# Import Discounting Parameters

path_params <- paste("../../data/", id, "_kappa.csv", sep="")
params <- read_csv(path_params)


##### REWARD
# Discount function plot
discount <- function(value, h, odds) {
  subj_value <- value * 1/(1+(h*odds))
  return(subj_value)
}

odds <- seq(0, 10, 0.1)
value <- 20
h_rew <- unlist(params[which(params$task=="reward"),'hh'])
sv <- discount(value, h_rew, odds)

discount_df <- tibble(odds, sv)

ggplot(discount_df, aes(x = odds, y = sv)) +
  geom_line(size = 1)

# Plot Generated Trials
# Run B generated from Python
trials %>% 
  filter(immOpt == 20 & task == "reward") %>% 
  ggplot(aes(x = probability, y = delOpt, color = p_cert)) +
  geom_point()

##### LOSS
# Discount function plot
odds <- seq(0, 10, 0.1)
value <- 20
h_loss <- unlist(params[which(params$task=="loss"),'hh'])
sv <- discount(value, h_loss, odds)

discount_df <- tibble(odds, sv)

ggplot(discount_df, aes(x = odds, y = sv)) +
  geom_line(size = 1)

# Plot Generated Trials
# Run B generated from Python
trials %>% 
  filter(immOpt == -20 & task == "loss") %>% 
  ggplot(aes(x = probability, y = delOpt, color = p_cert)) +
  geom_point()

# Flag problematic trials:
# uncertain < certain, < 0, NA/NaN, ...
trials <- trials %>% mutate(problem = ifelse(task == "reward", ifelse(delOpt <= immOpt, "problem", "check"),
                                             ifelse(delOpt >= immOpt, "problem", "check")))

# sort problematic trials by task, immOpt, probability, p_cert
trials %>%
  filter(task == "reward") %>% 
  group_by(immOpt, probability, p_cert) %>% 
  summarize(n = n())
